version: '{build}-{branch}'
image: Visual Studio 2017

skip_commits:
  files:
    - '**/*.md'

services: 
- mssql2017
- mysql

build_script:
- ps: dotnet build -c Release

test_script:
- ps: dotnet test test/* -c Release --no-build

after_test:
- ps: ./pack.ps1

artifacts:
- path: '**\artifacts\nuget\*.nupkg'
  name: NuGet
- path: '**\artifacts\myget\*.nupkg'
  name: MyGet

deploy:

- provider: NuGet
  api_key:
    secure: Dbkhn7AqBVkigVW1TKRHap/UUUSoIDdX0CE4PNKqBi6Yz4Ahcf0ptRNL6kIspMNQ
  artifact: NuGet
  on:
    appveyor_repo_tag: true
    
- provider: NuGet
  server: https://www.myget.org/F/phnx47-beta/api/v2/package
  api_key:
    secure: sra89qUYhiuc146gUszl0lg1u3tWG1Zc65B7lgVuZlIfxyq/3w4q3mkXeBiLpNA5
  symbol_server: https://www.myget.org/F/phnx47-beta/symbols/api/v2/package
  artifact: MyGet
  on:
    branch: master
    appveyor_repo_tag: false